# Custom config for RuboCop static code analysis
AllCops:
  TargetRubyVersion: 2.5

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Style/SignalException:
  EnforcedStyle: only_raise

Style/RaiseArgs:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/ModuleFunction:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/SwapValues:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/RescueException:
  Enabled: true
  Exclude:
    - 'lib/health_monitor/providers/**/*'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/EmptyClass:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true
